In [1]:
!pip install transformers

In [2]:
import torch

In [3]:
from transformers import BertTokenizer,BertModel

In [4]:
import random

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
##GPU Configuration:

random_seed=42

In [7]:
random.seed(random_seed)

In [8]:
torch.manual_seed(random_seed)

In [9]:
if torch.cuda.is_available():
  torch.cuda.manual_seed_all(random_seed)

In [11]:
##Loading the tokenzier:

tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [12]:
##Loading Model:

model=BertModel.from_pretrained("bert-base-uncased")

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [13]:
text="ineuron is for the best AI Courses."

In [14]:
encoding=tokenizer.batch_encode_plus([text],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [15]:
input_ids=encoding["input_ids"]

In [16]:
input_ids

tensor([[  101,  1999, 11236,  2239,  2003,  2005,  1996,  2190,  9932,  5352,
          1012,   102]])

In [17]:
attention_mask=encoding["attention_mask"]

In [18]:
with torch.no_grad():
  outputs=model(input_ids, attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state

In [19]:
word_embeddings.shape

torch.Size([1, 12, 768])

In [20]:
word_embeddings

tensor([[[-0.4270, -0.1666,  0.1909,  ..., -0.2987,  0.6356,  0.6963],
         [-0.4555, -0.5843,  0.3312,  ..., -0.1475,  0.5605,  1.2290],
         [-0.7174, -0.4126,  1.0531,  ...,  0.3063,  0.3983,  0.2660],
         ...,
         [ 0.3224,  0.1035,  0.5626,  ..., -0.2507, -0.0866, -0.3084],
         [ 0.5164,  0.1578, -0.0727,  ...,  0.2103, -0.4651, -0.2494],
         [ 0.2963,  0.2964,  0.2604,  ...,  0.3185, -0.6820, -0.1199]]])

In [25]:
input_ids[0]

tensor([  101,  1999, 11236,  2239,  2003,  2005,  1996,  2190,  9932,  5352,
         1012,   102])

In [26]:
decode=tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [23]:
decode

'ineuron is for the best ai courses.'